name: test

on: [push]

jobs:
  linux:
    name: test
    runs-on: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: setup
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: test
      run: |
        cp Examples/1_Electrostatic/1_Field_at_a_point_due_to_single_point_source/*.py src/
        cd src/
        python ./main.py
